default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8mb4
  pool: <%= ENV["MYSQL_POOL"] %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>

development:
  <<: *default
  database: react_development

test:
  <<: *default
  database: health_test

staging:
  <<: *default
  database: react_staging

production:
  <<: *default
  database: react_production